<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" Version="2.31.0" />
    <PackageReference Include="JsonPath.Net" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UnitTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CepMessageFormats\CepMessageFormats.csproj" />
    <ProjectReference Include="..\HttpMessageFormats\HttpMessageFormats.csproj" />
  </ItemGroup>

</Project>
