<Project Sdk="MSTest.Sdk/4.0.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CepMessageFormats\CepMessageFormats.csproj" />
    <ProjectReference Include="..\..\src\HttpMessageFormats\HttpMessageFormats.csproj" />
    <ProjectReference Include="..\..\src\Mcf\Mcf.csproj" />
    <ProjectReference Include="..\..\src\Mcf.Cli\Mcf.Cli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="examples\dotnet-request.cep">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\dotnet-response.cep">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\echo-request.cep">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\chain-request.http">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\httpbin-request.http">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\httpbin-response.http">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\ffmpeg-request.cep">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="examples\chain-request.mcf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
